### ISSUE TITLE
NullPointerException when computing references

### ISSUE THREAD

**Issue by jeff303** [visualvm/visualvm.src#4] opened 2016-10-24 18:54 UTC
I'm trying to analyze a large heap dump (file is around 60GB) using VisualVM 1.3.9.  There are a large number of int[] instances consuming the vast majority of the heap space, and I am trying to get to the bottom of why.  However, when I click on one of the instances in the instance view, which starts to determine the referrers, it makes it about 2% through and then throws a NullPointerException (as seen in the error button hover).  Full stack trace from logs:

```
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.profiler.heapwalk.model.BrowserUtils$1$1
java.lang.NullPointerException
    at org.netbeans.lib.profiler.heap.HprofHeap.computeReferences(HprofHeap.java:502)
    at org.netbeans.lib.profiler.heap.HprofHeap.findReferencesFor(HprofHeap.java:416)
    at org.netbeans.lib.profiler.heap.InstanceDump.getReferences(InstanceDump.java:116)
    at org.netbeans.modules.profiler.heapwalk.model.InstanceNode.getReferences(InstanceNode.java:144)
    at org.netbeans.modules.profiler.heapwalk.model.HeapWalkerNodeFactory.createReferences(HeapWalkerNodeFactory.java:353)
    at org.netbeans.modules.profiler.heapwalk.model.PrimitiveArrayNode$1.computeChildren(PrimitiveArrayNode.java:187)
    at org.netbeans.modules.profiler.heapwalk.model.BrowserUtils$1$1.run(BrowserUtils.java:301)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

If I navigate to the OQL window and try it that way via `referrers(heap.findObject("0x7fa8fb109ae0"))`, it runs for a while before printing:

`javax.script.ScriptException: ReferenceError: "println" is not defined in  at line number 1030`

Any ideas on what the problem could be or how I could diagnose further?  I am using Sun JDK 1.8.0_60 on Mac OS X, VisualVM 1.3.9.

**Comment by thurka** [comment] 2016-11-02 15:09
`javax.script.ScriptException` is tracked as [NetBeans issue #268791](https://netbeans.org/bugzilla/show_bug.cgi?id=268791).

**Comment by thurka** [comment] 2016-11-02 15:32
NPE is tracked as [NetBeans issue #254842](https://netbeans.org/bugzilla/show_bug.cgi?id=254842). This looks like broken heapdump, but it would be great if you can share (privately) the heapdump with us, so we can find out what is wrong. Thanks.

**Comment by jeff303** [comment] 2016-11-02 22:45
Unfortunately, I can't share the original heapdump.  However, I believe I can reproduce the problem with a new scenario that I can share.  I will reply when ready, and we can figure out how to share such a large file.

**Comment by thurka** [comment] 2017-02-01 08:01
Closing, if you have more info, please update the corresponding NetBeans issue.

**Closed by thurka** 2017-02-01 08:01 UTC

**Comment by eldilibra** [comment] 2017-08-16 21:51
The [NetBeans issue #254842](https://netbeans.org/bugzilla/show_bug.cgi?id=254842) mentioned above points the traveler back here. I just hit this as well.

**Comment by eldilibra** [comment] 2017-08-16 22:15
It looks like you guys bumped your NetBeans (NB) version in October 2016, but this issue was resolved in NB in November 2016. Could you update NB so users can take advantage of the bug fix, or perhaps give us some guidance on how to properly include a newer binary of NB into our local install of VisualVM (if that's possible)?

**Comment by thurka** [comment] 2017-08-17 08:08
Are you looking for the fix for NetBeans issue #268791? If so, you should be able to edit
hat_nashorn.js inside org-netbeans-modules-profiler-oql.jar and change println to print.
hat_nashorn.js is here:
`visualvm_139/profiler/modules/org-netbeans-modules-profiler-oql.jar:/org/netbeans/modules/profiler/oql/engine/api/impl/hat_nashorn.js`

**Comment by eldilibra** [comment] 2017-08-17 15:31
Thank you! I just tried this, and am now realizing that the NPE and the println -> print issue are not related. I'm still seeing this whenever I try to get references for an instance in this particular heapdump:
![image](https://user-images.githubusercontent.com/1389505/29420302-9914d530-833f-11e7-8510-d3ebbc0932fa.png)

Should I just assume I will not be able to resolve this with my current heapdump?

**Comment by thurka** [comment] 2017-08-17 15:41
Yes, NPE and the println -> print issue are not related. Therefore there are two separate NetBeans bugs.
As I wrote above, NPE suggests that it is caused by broken heapdump. Unfortunately without the heap dump, where I can reproduce it, I will not be able to confirm it.
